<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Title>Tanzy.Xunit extensions for xUnit v3</Title>
        <Description>xUnit v3 extensions that can be useful</Description>
        <PackageTags>xUnit xUnit.v3 Extensions</PackageTags>
        <IsPackable>true</IsPackable>
        <RepositoryUrl>https://github.com/Tanzy/Tanzy.Xunit</RepositoryUrl>
        <IsTestProject>false</IsTestProject>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <LangVersion>latestmajor</LangVersion>
        <Authors>Tanzy</Authors>
        <Copyright>Copyright 2021-2026</Copyright>
        <SonarQubeTestProject>false</SonarQubeTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3.extensibility.core" Version="4.0.0" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
