name: Scan dotNET using Snyk

on:
  push:
    branches: [ main ]
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
      - '.github/**'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Setup .NET
        uses: actions/setup-dotnet@4
        
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
          
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
